---
version: '2.4'
networks:
  test_default:
services:
  main-network:
    image: parity/parity:v2.3.3
    command: --config /app/parity_config.toml --unsafe-expose --tx-queue-per-sender=500
    working_dir: /app
    user: root
    restart: unless-stopped
    ports:
      - '8545:8545'
      - '8546:8546'
      - '30303:30303'
    volumes:
      - ./1/:/app/
    networks:
      - "test_default"
  side-network:
    image: parity/parity:v2.3.3
    command: --config /app/parity_config.toml --unsafe-expose --tx-queue-per-sender=500
    working_dir: /app
    user: root
    restart: unless-stopped
    ports:
      - '8547:8547'
      - '8548:8548'
      - '30304:30304'
    volumes:
      - ./2/:/app/
    networks:
      - "test_default"
