[parity]
keys_path = "/app/keys"
chain = "/app/chain.json"
auto_update = "none"

[network]
discovery = false
min_peers = 0
port = 30303

[rpc]
cors = ["all"]
apis = ["eth","net","private","parity","personal"] 
interface = "all"
port = 8545

[websockets]
disable = false
port = 8546

[ui]
disable = true

[account]
unlock = [ '0xde396059f282f58d67c850c0c65da85ea6ad90af' ]
password = ["/app/password.pwds"]

[misc]
logging = "own_tx=trace"
