[parity]
keys_path = "/app/keys"
chain = "/app/chain.json"
auto_update = "none"

[network]
discovery = true
min_peers = 0
port = 30304
reserved_peers = "./peers.txt"

[rpc]
cors = ["all"]
apis = ["eth","net","private","parity","personal"] 
interface = "all"
port = 8547

[websockets]
disable = false
port = 8548

[ui]
disable = true

[account]
unlock = [ '0xcd2e67289f9fadbc2917547b51cbc7a9a792c5d0',
           '0xde396059f282f58d67c850c0c65da85ea6ad90af' ]
password = ["/app/password.pwds"]

[mining]
engine_signer = "0xcd2e67289f9fadbc2917547b51cbc7a9a792c5d0"
author = "0xcd2e67289f9fadbc2917547b51cbc7a9a792c5d0"
reseal_on_txs = "none"
force_sealing = true

[misc]
logging = "own_tx=trace"
